# Generated by Django 6.0.6 on 2026-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='target_role',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
